resources:
- ../../base
- seal-credentials.yaml

patchesStrategicMerge:
- replicas_patch.yaml
- env_patch.yaml

namePrefix: staging-

images:
- name: peerapach/demo-workshop
  newTag: blue

commonLabels:
  env: staging
  test: abc
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
