apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-user
spec:
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
  #   canary: 
  #     steps:
  #     - setWeight: 20
  #     - pause: {}
  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: false      