apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example-prod

resources:
- ../../base
- namespace.yaml

patchesStrategicMerge:
- merge-patches/healthcheck-patch.yaml
- merge-patches/memorylimit-patch.yaml
- merge-patches/hpa-patch.yaml

namePrefix: production-

patchesJson6902:
- target:
    version: v1
    kind: Namespace
    name: example-prod
  path: patches/namespace-patch.yaml
- path: patches/ingress-annotations-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: app-user-ingress-active
    version: v1beta1

commonLabels:
  env: "production"      