resources:
- ../../base
- namespace.yaml
patchesStrategicMerge:
- healthcheck_patch.yaml
- memorylimit_patch.yaml
- replicas_patch.yaml
namePrefix: production-
patchesJson6902:
- target:
    version: v1
    kind: Namespace
    name: example-prod
  path: namespace_patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example-prod