apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: example-staging

configurations:
- rollout-transform.yaml

resources:
- ../../base
- namespace.yaml

patchesStrategicMerge:
- replicas_patch.yaml

namePrefix: staging-

images:
- name: peerapach/demo-workshop
  newTag: "4"

patchesJson6902:
- path: namespace_patch.yaml
  target:
    kind: Namespace
    name: example-staging
    version: v1
- path: ingress_patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: app-user-ingress
    version: v1beta1
- path: rm-deploy-common-label-in-selector.yaml
  target:
    group: argoproj.io
    kind: Rollout
    name: app-user
    version: v1alpha1
- path: rm-app-user-active-selector.yaml
  target:
    kind: Service
    name: app-user-active
    version: v1
- path: rm-app-user-active-selector.yaml
  target:
    kind: Service
    name: app-user-preview
    version: v1

commonLabels:
  env: staging
  test: "false"
