apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: example-staging

configurations:
- rollout-transform.yaml

resources:
- ../../base
- namespace.yaml

patchesStrategicMerge:
- replicas_patch.yaml

namePrefix: staging-

images:
- name: peerapach/demo-workshop
  newTag: "4"

patchesJson6902:
- path: namespace_patch.yaml
  target:
    kind: Namespace
    name: example-staging
    version: v1
- path: ingress_patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: app-user-ingress
    version: v1beta1

commonLabels:
  env: "staging"     
  test: "false"
  abc: "test"