apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: example-staging

configurations:
- rollout-transform.yaml

resources:
- ../../base
- namespace.yaml

patchesStrategicMerge:
- replicas_patch.yaml

namePrefix: staging-

images:
- name: peerapach/demo-workshop
  newTag: "10"

patchesJson6902:
- path: namespace_patch.yaml
  target:
    kind: Namespace
    name: example-staging
    version: v1
- path: ingress_patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: app-user-ingress
    version: v1beta1
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Rollout
    name: app-user
  path: rm-deploy-common-label-in-selector.yaml
- target:
    version: v1
    kind: Service
    name: app-user-active
  path: rm-app-user-active-selector.yaml
- target:
    version: v1
    kind: Service
    name: app-user-preview
  path: rm-app-user-active-selector.yaml  

commonLabels:
  env: "staging"     
  test: "false"