apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-user
spec:
  strategy:
    blueGreen: 
      activeService: staging-app-service-active
      previewService: staging-app-service-preview
      autoPromotionEnabled: false