apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: example-staging

resources:
- ../../base
- namespace.yaml

namePrefix: staging-

patchesJson6902:
- path: patches/namespace-patch.yaml
  target:
    kind: Namespace
    name: example-staging
    version: v1
- path: patches/ingress-annotations-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: app-user-ingress-active
    version: v1beta1
- path: patches/rm-labels-matchLabels-in-rollout.yaml
  target:
    group: argoproj.io
    kind: Rollout
    name: app-user
    version: v1alpha1
- path: patches/rm-selector-in-svc.yaml
  target:
    kind: Service
    name: app-user-active
    version: v1
- path: patches/rm-selector-in-svc.yaml
  target:
    kind: Service
    name: app-user-preview
    version: v1

commonLabels:
  env: staging
  test: "false"
