apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  name: argo-workflow-ci
  generateName: argo-workflow-ci--
spec:
  hostNetwork: true
  serviceAccountName: argo
  entrypoint: cicd
  volumes:
  - name: docker-config
    secret: 
      secretName: regcred
  arguments:
    parameters:
    - name: repo
      value: https://github.com/peerapach/ci-workshop.git
    - name: gitops-repo
      value: https://github.com/peerapach/gitops-argo.git
    - name: revision
      value: master
    - name: image-name-backend
      value: peerapach/argo-workflow
  templates:
  - name: cicd
    steps:
      - - name: checkout
          template: checkout
      - - name: build-push-docker
          template: build-push-docker
          arguments:
            artifacts:
            - name: git-repo
              from: "{{steps.checkout.outputs.artifacts.source}}"
            parameters:
            - name: image-tag
              value: "{{steps.checkout.outputs.parameters.tag}}"
      - - name: run-tests
          template: run-tests
          arguments:
            artifacts:
            - name: git-repo
              from: "{{steps.checkout.outputs.artifacts.source}}"
            parameters:
            - name: image-tag
              value: "{{steps.checkout.outputs.parameters.tag}}"
      - - name: deploy-kubernetes
          template: deploy-kubernetes
          arguments:
            artifacts:
            - name: gitops-repo
              from: "{{steps.checkout.outputs.artifacts.gitops-source}}"
            parameters:
            - name: image-tag
              value: "{{steps.checkout.outputs.parameters.tag}}"
  - name: checkout
    inputs:
      artifacts:
      - name: git-repo
        path: /src
        git:
          repo: "{{workflow.parameters.repo}}"
          revision: "{{workflow.parameters.revision}}"
      - name: gitops-repo
        path: /gitops
        git:
          repo: "{{workflow.parameters.gitops-repo}}"
          revision: "{{workflow.parameters.revision}}"          
    metadata:
      labels:
        app: argo
    container:
      image: alpine/git
      resources: 
        requests:
          cpu: 100m
          memory: 100Mi
        limits: 
          cpu: 400m
          memory: 800Mi
      command: [sh, -c]
      args: ["cd /src && git rev-parse --short HEAD > /tmp/git-commit"]
    outputs:
      artifacts:
      - name: source
        path: /src
      - name: gitops-source
        path: /gitops        
      parameters:
      - name: tag
        valueFrom:
          path: /tmp/git-commit
  - name: build-push-docker
    inputs:
      artifacts:
      - name: git-repo
        path: /src
      parameters:
      - name: image-tag
    metadata:
      labels:
        app: argo
    container:
      image: docker:18.09
      resources: 
        requests:
          cpu: 100m
          memory: 100Mi
        limits: 
          cpu: 400m
          memory: 800Mi
      workingDir: /src
      command: [sh, -c]
      args: ["until docker ps; do sleep 1; done; cd /src \ 
        && docker build . -t {{workflow.parameters.image-name-backend}}:{{inputs.parameters.image-tag}} && docker push {{workflow.parameters.image-name-backend}}:{{inputs.parameters.image-tag}}"]
      env:
      - name: DOCKER_HOST
        value: 127.0.0.1
      volumeMounts:
      - name: docker-config
        mountPath: /root/.docker/config.json
        subPath: .dockerconfigjson
    sidecars:
    - name: docker-in-docker
      image: docker:18.09-dind
      resources: 
        requests:
          cpu: 100m
          memory: 100Mi
        limits: 
          cpu: 400m
          memory: 800Mi
      securityContext:
        privileged: true
      mirrorVolumeMounts: true
  - name: run-tests
    inputs:
      artifacts:
      - name: git-repo
        path: /src
      parameters:
      - name: image-tag
    metadata:
      labels:
        app: argo
    container:
      image: peerapach/python:3.6
      workingDir: /src
      command: [sh, -c]
      args: ["cd src && \
              python -m unittest"]
  - name: deploy-kubernetes
    inputs:
      artifacts:
      - name: gitops-repo
        path: /gitops
      parameters:
      - name: image-tag
    metadata:
      labels:
        app: argo
    container:
      image: stefanprodan/kube-tools:v1.5.0
      resources: 
        requests:
          cpu: 100m
          memory: 100Mi
        limits: 
          cpu: 400m
          memory: 800Mi
      workingDir: /gitops
      command: [sh, -c]
      args: ["cd /gitops/kustomize-flask/base \
        && kustomize edit set image app-user={{workflow.parameters.image-name-backend}}:{{inputs.parameters.image-tag}} \
        && cat kustomization.yaml"]