apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:  
  project: default
  source:
    repoURL: 'git@github.com/peerapach/argo-example.git'
    path: kustomize-flask/overlays/staging
    targetRevision: develop
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: example-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
