apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:  
  project: default
  source:
    repoURL: 'https://github.com/peerapach/gitops-argo'
    path: kustomize-flask/base
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: example
  syncPolicy:
    automated:
      prune: true
      selfHeal: true