apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-user-hpa-rollout
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: app-user
  targetCPUUtilizationPercentage: 60