apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-user
spec:
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "250%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 1h # 1 hour
      - setWeight: 20
      - pause: {} # pause indefinitely