apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
- ingress.yaml

vars:
- name: ENV
  objref:
    kind: Deployment
    name: app-user
    apiVersion: apps/v1
  fieldref:
    fieldpath: metadata.labels['env']